# Generated by Django 5.1.3 on 2025-01-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(max_length=255, unique=True)),
                ('setting_type', models.CharField(choices=[('char', 'CharField'), ('bool', 'BooleanField'), ('int', 'IntegerField'), ('float', 'FloatField')], max_length=10)),
                ('char_value', models.CharField(blank=True, max_length=255, null=True)),
                ('bool_value', models.BooleanField(blank=True, null=True)),
                ('int_value', models.IntegerField(blank=True, null=True)),
                ('float_value', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
