# Generated by Django 5.1.3 on 2025-01-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsetting',
            name='setting_type',
            field=models.CharField(choices=[('char', 'CharField'), ('bool', 'BooleanField'), ('int', 'IntegerField'), ('float', 'FloatField')], max_length=255),
        ),
    ]
