# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/reuse-lint.yml

autotest:
  stage: "build"
  variables:
     FF_NETWORK_PER_BUILD: 1
     AMQP_URL: amqp://amqp
     POSTGRES_DATABASE: foss-public-alert-server
     POSTGRES_HOST: db
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: password
  services:
    - name: postgis/postgis:14-3.2
      alias: db
      variables:
        POSTGRES_DB: foss-public-alert-server
    - name: rabbitmq
      alias: amqp
  image: python:3.10-bullseye
  before_script:
     - apt-get update && apt-get -y install libgdal-dev
     - pip install -r foss_public_alert_server/requirements.txt
  script:
     - cd foss_public_alert_server
     - cd lib && PYTHONPATH=$PYTHONPATH:.. python3 -m unittest discover && cd ..
     - python3 manage.py test

container:
  stage: "publish"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
  image: storage.kde.org/vm-images/image-builder
  tags:
    - VM
    - amd64
  variables:
    IMAGE_TAG: latest
    IMAGE_NAME: foss-public-alert-server
  script:
    - podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - podman build --pull --build-arg REVISION="$CI_COMMIT_SHORT_SHA" --no-cache --tag ${CI_REGISTRY}/${CI_PROJECT_PATH}/${IMAGE_NAME}:${IMAGE_TAG} foss_public_alert_server/
    - podman push ${CI_REGISTRY}/${CI_PROJECT_PATH}/${IMAGE_NAME}:${IMAGE_TAG}
