# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

stages:
  - validate
  - test
  - publish

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/reuse-lint.yml

# run the django unit tests
autotest:
  stage: test
  variables:
     FF_NETWORK_PER_BUILD: 1
     AMQP_URL: amqp://amqp
     POSTGRES_DATABASE: foss-public-alert-server
     POSTGRES_HOST: db
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: password
  services:
    - name: postgis/postgis:14-3.2
      alias: db
      variables:
        POSTGRES_DB: foss-public-alert-server
    - name: rabbitmq:4.2
      alias: amqp
  image: python:3.14-trixie
  before_script:
     - echo "Prepare environment"
     - apt-get update && apt-get -y install libgdal-dev
     - curl -LsSf https://astral.sh/uv/install.sh | sh
     - source $HOME/.local/bin/env # add uv to path
     - cd foss_public_alert_server
     - uv sync
  script:
     - echo "Run unit tests"
     - cd lib && PYTHONPATH=$PYTHONPATH:.. uv run -m unittest discover && cd ..
     - uv run manage.py test

# run the formatter
format-job:
  stage: test

  image: python:3.14-trixie
  before_script:
    - echo "Prepare environment"
    - apt-get update && apt-get -y install libgdal-dev
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - source $HOME/.local/bin/env # add uv to path
    - cd foss_public_alert_server
    - uv sync
  script:
    - echo "Run formatter"
    - uv run ruff format --check

# run the linter
linting-job:
  stage: test

  image: python:3.14-trixie
  before_script:
    - echo "Prepare environment"
    - apt-get update && apt-get -y install libgdal-dev
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - source $HOME/.local/bin/env # add uv to path
    - cd foss_public_alert_server
    - uv sync
  script:
    - echo "Run linter"
    - uv run ruff check -e # exit with zero even upon detecting violations just until we fixed the issues


# build the container image and push to server
container:
  stage: publish
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
  image: storage.kde.org/vm-images/image-builder
  tags:
    - VM
    - amd64
  variables:
    IMAGE_TAG: latest
    IMAGE_NAME: foss-public-alert-server
  script:
    - podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - podman build --pull --build-arg REVISION="$CI_COMMIT_SHORT_SHA" --no-cache --tag ${CI_REGISTRY}/${CI_PROJECT_PATH}/${IMAGE_NAME}:${IMAGE_TAG} foss_public_alert_server/
    - podman push ${CI_REGISTRY}/${CI_PROJECT_PATH}/${IMAGE_NAME}:${IMAGE_TAG}
