# Generated by Django 5.0.4 on 2024-04-26 14:03

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('041f9404-e46d-4005-8bfb-1e15bfef2835'), editable=False, primary_key=True, serialize=False)),
                ('bounding_box', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('distributor_url', models.CharField(max_length=255)),
            ],
        ),
    ]
