# Generated by Django 5.1.3 on 2025-01-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionHandler', '0002_subscription_last_heartbeat_alter_subscription_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='distributor_url',
            new_name='token',
        ),
        migrations.AddField(
            model_name='subscription',
            name='push_service',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
