# Generated by Django 5.1.1 on 2025-02-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscriptionHandler",
            "0002_subscription_last_heartbeat_alter_subscription_id",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="distributor_url",
            new_name="token",
        ),
        migrations.AddField(
            model_name="subscription",
            name="push_service",
            field=models.IntegerField(
                choices=[
                    (0, "UNIFIED_PUSH"),
                    (1, "UNIFIED_PUSH_ENCRYPTED"),
                    (2, "APN"),
                    (3, "FIREBASE"),
                ],
                default=0,
            ),
        ),
    ]
