# Generated by Django 5.1.3 on 2025-02-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionHandler', '0003_rename_distributor_url_subscription_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='token',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
