# Generated by Django 5.1.3 on 2025-06-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('subscriptionHandler', '0005_subscription_error_counter_and_more'), ('subscriptionHandler', '0006_alter_subscription_error_counter')]

    dependencies = [
        ('subscriptionHandler', '0004_subscription_auth_key_subscription_p256dh_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='error_messages',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='error_counter',
            field=models.IntegerField(default=0),
        ),
    ]
