# Generated by Django 5.1.3 on 2025-02-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionHandler', '0004_alter_subscription_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='push_service',
            field=models.IntegerField(choices=[(0, 'UnifiedPush'), (1, 'UnifiedPush_encrypted'), (2, 'APN'), (3, 'Firebase')], default=None),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
