# Generated by Django 5.1.3 on 2025-09-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionHandler', '0006_connectionflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='token',
            field=models.CharField(max_length=2048),
        ),
    ]
