# Generated by Django 5.1.3 on 2025-11-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionHandler', '0007_alter_subscription_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='user_agent',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
