# Generated by Django 5.1.3 on 2025-11-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionHandler', '0008_subscription_user_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectionflag',
            name='id',
        ),
        migrations.AlterField(
            model_name='connectionflag',
            name='hostname',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
