# Generated by Django 5.1.3 on 2025-12-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionHandler', '0009_remove_connectionflag_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionflag',
            name='error_message',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
