# Generated by Django 5.2.14 on 2026-08-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionHandler', '0012_subcription_vapid_public_key_fill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectionflag',
            name='time_out',
        ),
        migrations.AddField(
            model_name='connectionflag',
            name='type',
            field=models.IntegerField(choices=[(0, 'TIME_OUT'), (1, 'RATE_LIMIT')], default=0),
        ),
    ]
