# Generated by Django 5.2.14 on 2026-08-30 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionHandler', '0013_remove_connectionflag_time_out_connectionflag_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionflag',
            name='expire_time_stamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
