# Generated by Django 5.1.3 on 2025-03-31 17:12

import alertTester.models
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapFeed',
            fields=[
                ('source_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alertTester.capfeed')),
                ('alert_id', models.CharField(max_length=255)),
                ('areaDesc', models.CharField(max_length=255)),
                ('cap_data', models.FileField(null=True, upload_to=alertTester.models.alert_upload_path)),
                ('sent', models.DateTimeField()),
                ('expires', models.DateTimeField(null=True)),
                ('msg_type', models.CharField(choices=[('Alert', 'Alert'), ('Update', 'Update'), ('Cancel', 'Cancel'), ('Ack', 'Ack'), ('Error', 'Error')], default='Alert', max_length=15)),
                ('status', models.CharField(choices=[('Actual', 'Actual'), ('Exercise', 'Exercise'), ('System', 'System'), ('Test', 'Test'), ('Draft', 'Draft')], default='Test', max_length=15)),
                ('event', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('Extreme', 'Extreme'), ('Severe', 'Severe'), ('Moderate', 'Moderate'), ('Minor', 'Minor'), ('Unknown', 'Unknown')], default='Unknown', max_length=15)),
                ('urgency', models.CharField(choices=[('Immediate', 'Immediate'), ('Expected', 'Expected'), ('Future', 'Future'), ('Past', 'Past'), ('Unknown', 'Unknown')], default='Unknown', max_length=15)),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('headline', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=512)),
                ('category', models.CharField(choices=[('Geo', 'Geo'), ('Met', 'Met'), ('Safety', 'Safety'), ('Security', 'Security'), ('Rescue', 'Rescue'), ('Fire', 'Fire'), ('Health', 'Health'), ('Env', 'Env'), ('Transport', 'Transport'), ('Infra', 'Infra'), ('CBRNE', 'Cbrne'), ('Other', 'Other')], default='Other', max_length=15)),
                ('certainty', models.CharField(choices=[('Observed', 'Observed'), ('Likely', 'Likely'), ('Possible', 'Possible'), ('Unlikely', 'Unlikely'), ('Unknown', 'Unknown')], default='Unknown', max_length=15)),
                ('onset', models.DateTimeField(null=True)),
                ('scope', models.CharField(choices=[('Public', 'Public'), ('Restricted', 'Restricted'), ('Private', 'Private')], default='Public', max_length=15)),
                ('sender', models.CharField(max_length=255)),
            ],
        ),
    ]