# Generated by Django 5.1.1 on 2024-11-09 12:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CAPFeedSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_id", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("logo", models.CharField(max_length=255, null=True)),
                ("guid", models.CharField(max_length=255, null=True)),
                ("register_url", models.CharField(max_length=255, null=True)),
                ("source_is_official", models.BooleanField(null=True)),
                ("cap_alert_feed", models.CharField(max_length=255)),
                ("cap_alert_feed_status", models.CharField(max_length=255)),
                ("authorityCountry", models.CharField(max_length=255)),
                ("authorityAbbrev", models.CharField(max_length=255)),
                ("feedSource", models.CharField(max_length=255)),
                ("format", models.CharField(max_length=255)),
                ("ignore", models.BooleanField(null=True)),
                ("last_fetch_status", models.BooleanField(null=True)),
                ("last_fetch_duration", models.DurationField(null=True)),
                ("missing_geo_information", models.BooleanField(null=True)),
                ("feed_warnings", models.CharField(max_length=255, null=True)),
                ("last_e_tag", models.CharField(max_length=255, null=True)),
                ("periodic_task_name", models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
