# Generated by Django 5.1.3 on 2024-12-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourceFeedHandler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capfeedsource',
            name='latest_published_alert_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
