# Generated by Django 5.1.3 on 2024-12-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourceFeedHandler', '0003_alter_capfeedsource_feed_warnings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capfeedsource',
            name='guid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
