# Generated by Django 5.1.4 on 2024-12-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourceFeedHandler', '0004_alter_capfeedsource_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capfeedsource',
            name='source_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
