# Generated by Django 5.0.4 on 2024-04-26 14:03

import alertHandler.models
import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_id', models.CharField(max_length=255)),
                ('alert_id', models.CharField(max_length=255)),
                ('bounding_box', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('cap_data', models.FileField(null=True, upload_to=alertHandler.models.alert_upload_path)),
                ('issue_time', models.DateTimeField()),
                ('expire_time', models.DateTimeField(null=True)),
                ('source_url', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(models.F('source_id'), models.F('alert_id'), name='source_id-alert_id-unique'),
        ),
    ]
