# Generated by Django 5.0.4 on 2024-04-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertHandler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='cap_data_modified',
            field=models.BooleanField(null=True),
        ),
    ]
