# Generated by Django 5.1.4 on 2025-02-15 15:53

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alertHandler', '0002_alert_cap_data_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
