# Generated by Django 5.1.4 on 2025-02-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertHandler', '0003_alert_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='event',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='msg_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='severity',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='urgency',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
