# Generated by Django 5.1.1 on 2025-03-05 13:51

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alertHandler", "0003_alert_event_alert_msg_type_alert_severity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="area",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                null=True, srid=4326
            ),
        ),
    ]
