# Generated by Django 5.2.2 on 2025-10-01 13:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models
from django.contrib.gis.geos import MultiPolygon


class Migration(migrations.Migration):

    dependencies = [
        ("alertHandler", "0004_alert_area"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alert",
            name="bounding_box",
        ),
        migrations.AlterField(
            model_name="alert",
            name="area",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                default=MultiPolygon(), srid=4326
            ),
            preserve_default=False,
        ),
    ]
